# Generated by Django 4.0.5 on 2022-06-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_alter_userdetail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='rzrp_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
