# Generated by Django 4.0.5 on 2022-06-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_userdetail_rzrp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='rzrp_details',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
